title: Amy Leaver # your name (or website title) here
logo: "/images/square_head.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst 
  <br><br>
  Passionate about data science and analytics, I bring a decade of teaching experience,
  a strong foundation in mathematics and a keen eye for detail to the field. 
  <br><br>
  <a href="http://www.linkedin.com/in/amy-leaver">View My LinkedIn Profile</a> 


  <br><br>
  Skills:
  Languages: Python (Pandas, NumPy, Matplotlib), SQL, R
  Data Collections: CSV, Web-scraping
  Data Visualization: MatplotLib, Seaborn, Plotly, Tableau, PowerBI DBMS: MySQL, PostgreSQL
  Analytical Tools: SQL, Python, Tableau, PowerBI, Advanced Excel
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
